before_script:
  - npm install -g bower
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - bower install -f
language: ruby
services:
  - redis-server
rvm:
  - ruby-head
  - 2.1.5
matrix:
  allow_failures:
    - rvm: ruby-head