base: &common
  redis: &redis
    namespace: entaku
  fluent: &fluent
    appname: app
  gtm: "GTM-"

development:
  <<: *common
  host: localhost:9292
  root: "./"
  protocol: "http"
  redis:
    <<: *redis
    host: localhost
    port: 6379
  fluent:
    <<: *fluent
    host: localhost
    port: 24224

test:
  <<: *common
  host: localhost:9292
  root: "./"
  protocol: "http"
  redis:
    <<: *redis
    host: localhost
    port: 6379
  fluent:
    <<: *fluent
    host: localhost
    port: 24224

staging:
  <<: *common
  host: localhost:9292
  root: "./"
  protocol: "http"
  redis:
    <<: *redis
    host: localhost
    port: 6379
  fluent:
    <<: *fluent
    host: localhost
    port: 24224

production:
  <<: *common
  host: localhost:9292
  root: "./"
  protocol: "http"
  redis:
    <<: *redis
    host: localhost
    port: 6379
  fluent:
    <<: *fluent
    host: localhost
    port: 24224
